
spring:
  profiles:
    active: dev
    # active: prod
  application:
    name: myJournalProject

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://usermangesh:passwordmangesh@cluster0.kusme.mongodb.net/myJournalProject?retryWrites=true&w=majority&appName=Cluster0

  main:
    allow-circular-references: true

weather:
  api:
    Key: 90e812b9afcf7e47415ec15d0613255f

# logging:
#   level:
#     root: ERROR
#     com:
#       myproject:
#         myJournalProject:
#           services:
#             UserService: ERROR
#     org:
#       springframework:
#         web: DEBUG
#         security: DEBUG
#     # process id -- thread info -- package -- log {SYNTAX OF LOGGING}

