
spring:
  profiles:
    active: dev
    # active: prod
  application:
    name: myJournalProject

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://usermangesh:passwordmangesh@cluster0.kusme.mongodb.net/myJournalProject?retryWrites=true&w=majority&appName=Cluster0

  main:
    allow-circular-references: true

logging:
  level:
    org:
    # process id -- thread info -- package -- log {SYNTAX OF LOGGING}
      springframework:
        web: DEBUG
        security: DEBUG

